export class Car {
    name: string = ""
    pictures: string = ""
    power: number = 0
    nb_horses: number = 0
    nb_kms: number = 0
    first_registration_date: string = ""
    nb_seating_places: number = 0
    nb_doors: number = 0
    co2: number = 0
    regular_price: number = 0
    currency: string = ""
    created: string = ""
    fuelId: number = 0
    extcolorId: number = 0
    intcolorId: number = 0
    transmissionId: number = 0
    brandId: number = 0
    modelId: number = 0
    stateId: number = 0
    chassisId: number = 0
    equipmentId: number = 0
    equipmentCategoryId: number = 0
    userId: number = 0
}
